### ISSUE TITLE
Angular vs. React

### ISSUE THREAD

**Issue by tvandenbrande** [gelukszaaiers/clientside#4]
Decide wether to use Angular.js or React to use to build the user interfact.

**Comment by tvandenbrande** [comment]
Based on most documentation: reactJs

**Comment by samover** [comment]
I would use React Native, assuming that developers involved will have knowledge of JS. Know that developing mobile apps through JS is not always an easy endeavour and that two native devs (Android + IOS) would probably be a faster solution (provided we have two native devs :-D )
